### ISSUE TITLE
[UI] Cannot see logs on iPhone

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#655] opened 2017-07-20 17:53 UTC
Cannot see build logs on iPhone. I click on the step but nothing happens.

Logs load without problem on Ian's Android phone.

**Comment by petey** [comment] 2017-07-28 18:10
I think we may not be listening to the correct Safari UIWebComponent events to process the clicks in that component.

**Comment by stjohnjohnson** [comment] 2018-03-12 07:15
Duplicate of https://github.com/screwdriver-cd/screwdriver/issues/486

**Closed by stjohnjohnson** 2018-03-12 07:15 UTC
Labels: bug
