### ISSUE TITLE
Improve step log load time

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1114] opened 2018-06-11 20:06 UTC
## Context

Loading step logs is slow for steps which generates large number of log lines. This is because we store step logs as files with 100 lines per file. Also we lack metadata on number of log files per step. This results in UI issues requests to read step logs file by file until we reach end of files, which makes loading step logs really slow for steps with large number of lines. 

UI waits to load entire log for a step before it scrolls to bottom to show latest, which does not perform well because of above reasons. So we need a way to just show latest logs without having to download the entire logs and progressively load rest of them. 

## Objective

 - [x] Reduce number of files generated per step. #1043
 - [x] Store number of log files for a step in a metadata file per step.
 - [x] Use metadata file to load latest logs first.
 - [x] Load logs in reverse in UI
 - [x] Start loading older logs when user starts scrolling.
 - [x] Option to download a step's log

## References
1. https://github.com/screwdriver-cd/screwdriver/issues/953
1. https://github.com/screwdriver-cd/screwdriver/issues/1024
1. https://github.com/screwdriver-cd/screwdriver/issues/1043

**Comment by catto** [comment] 2018-06-26 07:17
I found a bug that the latest api and log-service combination cannot handle old logs that have 100+ lines. I confirmed that logs from a new build work fine.
https://cd.screwdriver.cd/pipelines/1/builds/44579
Is this a breaking change? #1043

**Comment by vengopal** [comment] 2018-07-03 01:22
@minz1027 @jithin1987   can we please reply for @catto .

**Comment by tkyi** [comment] 2018-07-23 17:57
@catto Sorry, I think @minz1027 commented in one of her PRs saying that the new API needed to be pulled in before the new launcher (https://github.com/screwdriver-cd/screwdriver/pull/1134#issue-196302740).

**Comment by minz1027** [comment] 2018-07-23 18:44
### Updates 07/23

Will do the optimization for finished build step first. We will update number of pages for a step log when step finishes. For finished step, UI will call API to fetch logs from the last page. And when user scroll up then go fetch the previous page.

- [ ] `data-schema`: add `pages` in build step meta
- [ ]  `log-service`: take in api url to update build step meta
- [ ] `api`: support load logs from the end
- [ ] `ui`: fetch logs from the end for finished steps

**Comment by catto** [comment] 2018-07-26 05:49
@tkyi Thanks for your comment, but I meant to say it seems that there is no backward compatibility.
Please see your cluster: https://cd.screwdriver.cd/pipelines/1/builds/44579 
This is an old build before the upgrade. `test` step shows only first 100 lines even if both API and launcher has been upgraded.
![image](https://user-images.githubusercontent.com/1608595/43243697-d75e9ff4-90e2-11e8-88d5-b29cb1b37b94.png)

**Comment by minz1027** [comment] 2018-07-26 06:50
@catto The build your mentioned is a special one. That one build is broken because we pulled in the launcher before the API change is merged. If you guys pull in the API first and then Launcher as what i documented in my PR, there won't be missing logs. 
For example, builds from 2 months ago: https://cd.screwdriver.cd/pipelines/1/builds/41405

**Comment by minz1027** [comment] 2018-07-26 07:04
@catto the behavior is kinda weird. If you load this link https://cd.screwdriver.cd/pipelines/1/builds/44579 multiple times and open that step. Sometimes you will see the full log. I don't know why... Need to investigate a bit. Sometimes the API is only returning the first 100 lines and sometimes API is returning more.

<img width="858" alt="screen shot 2018-07-26 at 12 02 18 am" src="https://user-images.githubusercontent.com/20427140/43246702-5119417c-9067-11e8-99d9-f2a2bcabc91b.png">

**Comment by minz1027** [comment] 2018-07-26 20:43
@catto Ah... there is a bug in the code. I have fixed it with this PR https://github.com/screwdriver-cd/screwdriver/commit/eeaa1ab900900a6cf91e42ce50b0ad42f5bd6b71. 

Now https://cd.screwdriver.cd/pipelines/1/builds/44579 should always give you the full log. Thanks for reporting this!

**Comment by catto** [comment] 2018-07-30 02:54
@minz1027 Thanks for the investigation and the fix!

**Closed** 2018-09-17 19:55 UTC
Labels: UX, feature

**Comment by tkyi** [comment] 2018-09-18 17:16
Available with UI v1.0.329
