### ISSUE TITLE
[Feature Request] Deprecated Template

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1989] opened 2020-02-28 02:54 UTC
**What happened**:
Even if we mark template as deprecated in description of template, users who use that template cannot notice that template is deprecated in the build or the pipeline page.

**What you expected to happen**:
Users who use deprecated template can notice that they use deprecated template in the build or the pipeline page.

For example:
1. Some templates are marked as deprecated.
2. Users use those template.
3. The build or the pipeline page shows that "You are using deprecated template."

**How to reproduce it**:
N/A

**Comment by jithine** [comment] 2021-11-30 13:20
Duplicate of https://github.com/screwdriver-cd/screwdriver/issues/1490

**Closed by jithine** 2021-11-30 13:21 UTC
Labels: feature
