### ISSUE TITLE
Issue deploying new sd-in-a-box

### ISSUE THREAD

**Issue by mrmastii** [screwdriver-cd/screwdriver#2363] opened 2021-03-01 22:23 UTC
**What happened:**
While deploying SD in box for a PoC, I got following error
Pulling api   ... done
Pulling ui    ... done
Pulling store ... done
Creating screwdriver_store_1 ... done
Creating screwdriver_api_1   ... done
Creating screwdriver_ui_1    ... done
**Couldn't get a file descriptor referring to the console**

**What you expected to happen:**
I presume three pods should be up and running, however I see only one

[ec2-user@ip-10-0-10-253 ~]$ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                  NAMES
180b4dd9ffa4        screwdrivercd/ui:stable   "nginx -g 'daemon of…"   2 hours ago         Up 2 hours          0.0.0.0:9000->80/tcp   screwdriver_ui_1
[ec2-user@ip-10-0-10-253 ~]$ 

List if images 
[ec2-user@ip-10-0-10-253 ~]$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
screwdrivercd/ui            stable              ad09c5b07ecd        2 weeks ago         26.2MB
screwdrivercd/screwdriver   stable              16b5b7dcd546        2 weeks ago         1.1GB
screwdrivercd/store         stable              e7dbcc23062c        2 months ago        1.06GB
[ec2-user@ip-10-0-10-253 ~]$ 

**How to reproduce it:**
Instruction used : https://github.com/screwdriver-cd/in-a-box#screwdriver-in-a-box

**Comment by mrmastii** [comment] 2021-03-01 22:26
Error from : screwdrivercd/screwdriver


> screwdriver-api@4.1.49 start /usr/src/app/node_modules/screwdriver-api
> ./bin/server

/usr/src/app/node_modules/screwdriver-api/bin/server:63
const notificationsValidationErr = hoek.reach(config.get('notifications').options, 'throwValidationErr'); // flag to throw notifications validation err or not
                                                                         ^

TypeError: Cannot read property 'options' of null
    at Object.<anonymous> (/usr/src/app/node_modules/screwdriver-api/bin/server:63:74)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! screwdriver-api@4.1.49 start: `./bin/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the screwdriver-api@4.1.49 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-01T22_24_47_286Z-debug.log

**Comment by mrmastii** [comment] 2021-03-01 22:26
Error from : Store.

> screwdriver-store@4.0.1 start /usr/src/app/node_modules/screwdriver-store
> ./bin/server

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'catbox-memory'
Require stack:
- /usr/src/app/node_modules/screwdriver-store/bin/server
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/screwdriver-store/bin/server:13:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/node_modules/screwdriver-store/bin/server' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! screwdriver-store@4.0.1 start: `./bin/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the screwdriver-store@4.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-01T22_26_24_464Z-debug.log

**Comment by momocow** [comment] 2021-03-02 15:51
Same here using image, `screwdrivercd/screwdriver:stable`, from Dockerhub.

```

> screwdriver-api@4.1.49 start /usr/src/app/node_modules/screwdriver-api
> ./bin/server
/usr/src/app/node_modules/screwdriver-api/bin/server:63
const notificationsValidationErr = hoek.reach(config.get('notifications').options, 'throwValidationErr'); // flag to throw notifications validation err or not
                                                                         ^

TypeError: Cannot read property 'options' of null
    at Object.<anonymous> (/usr/src/app/node_modules/screwdriver-api/bin/server:63:74)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! screwdriver-api@4.1.49 start: `./bin/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the screwdriver-api@4.1.49 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-02T15_43_55_880Z-debug.log
```

**Comment by momocow** [comment] 2021-03-02 15:54
It may be related to #2340.

**Comment by jithine** [comment] 2021-03-02 16:04
@klu909 can you take a look at what's going on ?

**Comment by jithine** [comment] 2021-03-02 16:06
I've retagged stable version. So API should be good. But the store seems to be caused by this issue https://github.com/screwdriver-cd/screwdriver/issues/2358 We need to fix that. @klu909 @kumada626

**Comment by klu909** [comment] 2021-03-03 19:23
> Same here using image, `screwdrivercd/screwdriver:stable`, pulled today from Dockerhub.
> 
> ```
> 
> > screwdriver-api@4.1.49 start /usr/src/app/node_modules/screwdriver-api
> > ./bin/server
> /usr/src/app/node_modules/screwdriver-api/bin/server:63
> const notificationsValidationErr = hoek.reach(config.get('notifications').options, 'throwValidationErr'); // flag to throw notifications validation err or not
>                                                                          ^
> 
> TypeError: Cannot read property 'options' of null
>     at Object.<anonymous> (/usr/src/app/node_modules/screwdriver-api/bin/server:63:74)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
>     at internal/main/run_main_module.js:17:47
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! screwdriver-api@4.1.49 start: `./bin/server`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the screwdriver-api@4.1.49 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-03-02T15_43_55_880Z-debug.log
> ```

this was fixed in this pr https://github.com/screwdriver-cd/screwdriver/pull/2355, we will have to update stable tag to fix this

**Comment by jithine** [comment] 2021-03-03 22:24
stable tags for ui/api/store moved to latest. Thanks @klu909 for fixing store. @mrmastii can you try again ?

**Closed** 2021-03-09 20:53 UTC
Labels: bug
