### ISSUE TITLE
in-a-box instruction is github specific

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#332] opened 2016-10-31 18:02 UTC
<img width="559" alt="screen shot 2016-10-31 at 11 01 22 am" src="https://cloud.githubusercontent.com/assets/20427140/19865435/721dd442-9f59-11e6-933a-0a51ee48aec3.png">

**Comment by stjohnjohnson** [comment] 2016-10-31 18:12
This ties directly to https://github.com/screwdriver-cd/screwdriver/issues/321

**Comment by d2lam** [comment] 2016-10-31 18:22
Duplicate of https://github.com/screwdriver-cd/screwdriver/issues/321

**Closed by d2lam** 2016-10-31 18:22 UTC
