### ISSUE TITLE
secrets values is evaluated

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1670] opened 2019-06-06 06:02 UTC
**What happened**:
I preserve secret data in SD secret. If the secret data has `$.*`, it was evaluated and the secret values has changed.

**What you expected to happen**:
Secret values will not be changed.

**How to reproduce it**:
Preserve data to SD secret which include `$.*` string.

**Comment by catto** [comment] 2019-06-07 07:30
The problem is that users cannot set a secret string to SD secrets such as password and token.
Some passwords include `$` character in it for instance `8a92a5f318$bdbd1e/0a28a9ac7c0_648`.
In this case, `$bdbd1e` will be evaluated by launcher and the password will change into `8a92a5f318/0a28a9ac7c0_648`. It is hard for users to use their correct password via SD secrets.

https://github.com/screwdriver-cd/launcher/blob/21f464ea291f3a2bc907bedf7c4ce0ef9be295cd/launch.go#L467

**Comment by tk3fftk** [comment] 2019-06-11 00:30
This might be fixed in launcher `v6.0.7`.

**Closed** 2019-06-13 22:35 UTC
Labels: bug
