### ISSUE TITLE
[Collections] Number of pull requests vs. number of jobs

### ISSUE THREAD

**Issue by edudar** [screwdriver-cd/screwdriver#1083] opened 2018-05-23 23:01 UTC
**What happened**:
Collection page shows a number that is supposed to be number of open pull requests but that's not correct as I have only 1 pull request opened.
<img width="348" alt="screen shot 2018-05-23 at 3 52 34 pm" src="https://user-images.githubusercontent.com/584181/40455483-f6fd34f6-5ea1-11e8-92e2-04052d169ea2.png">

**What you expected to happen**:
It's either:
1) That number should be `1` as I have 1 pull request only but it has 3 jobs
2) That label should say something like `Jobs` and be 3 as it's now
3) Shows both pull requests that would be `1` and jobs per pull requests that would be `3`
4) Something else to make it clear what `3` is.

**How to reproduce it**:
Create a pipeline with multiple jobs. Add pipeline to a collection. Create a pull request.

**Comment by tkyi** [comment] 2018-07-03 21:57
@edudar I can't seem to reproduce this issue. Are you still seeing this problem?

**Comment by tkyi** [comment] 2018-07-05 20:44
Going to close the issue since it doesn't seem to still be relevant. Feel free to reopen if you see it again.

**Closed by tkyi** 2018-07-05 20:44 UTC

**Comment by edudar** [comment] 2018-07-11 18:38
It's clearly an issue. I have 2 PR opened that are shows as 6 on the dashboard because of 3 jobs per PR
