### ISSUE TITLE
The UI does strange things with scrolling

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#235] opened 2016-10-03 19:21 UTC
- When I first showed up to the page, it didn't seem to be auto-scrolling.
- After scrolling to the bottom, I saw an error fly by, so I scrolled up
- Then the window scrolled down
- But not to the very bottom. It was like 3 lines from the bottom.

It would be fantastic if we just allow scrolling up to disable auto-scroll. Whenever you are scrolled to within a handful of lines from the bottom, it locks in auto-scrolling.

**Comment by petey** [comment] 2016-10-03 20:47
I think the "not-scrolling" behavior is being caused by the rendering of new lines occurring after the scroll is triggered. I will look into this. Probably need to use `Ember.run.scheduleOnce` for scrolling.

**Comment by petey** [comment] 2016-10-06 00:17
Should be fixed now.

**Closed by petey** 2016-10-06 00:17 UTC
Labels: priority/medium, type/bug
