### ISSUE TITLE
sd-cmd commands expire after 1 year, even if used consistently

### ISSUE THREAD

**Issue by stolfi** [screwdriver-cd/screwdriver#1885] opened 2019-12-18 15:55 UTC
**What happened**:
An sd-cmd that I had published a year ago stopped working, even under consistent (daily) use. There is no mention of this in the documentation.

**What you expected to happen**:
I expected the command to remain available. I understand the desire to expire things, but I feel it should be done on a time and usage basis (not run for 6 months, etc).

**How to reproduce it**:
Publish a new cmd, wait a year and a day :-)

**Changes I would like to see**:
- Things that are running consistently should never expire.
- The documentation should be updated.

**Comment by jithine** [comment] 2020-01-10 22:21
I agree that recently used commands should not expire. We could get to this when we work on https://github.com/screwdriver-cd/screwdriver/issues/1091

**Comment by hk-vmg** [comment] 2020-07-17 23:20
See #2058

**Comment by jithine** [comment] 2021-03-12 02:25
Duplicate of https://github.com/screwdriver-cd/screwdriver/issues/2058

**Closed by jithine** 2021-03-12 02:25 UTC
Labels: bug
