### ISSUE TITLE
[FEAT] Virtual Trigger Job

### ISSUE THREAD

**Issue by renaud-vmg** [screwdriver-cd/screwdriver#2470] opened 2021-06-03 18:40 UTC
**Why?**

Mostly as a UX enhancement. When a job specifies a "requires" with a job name that doesn't exist, Screwdriver could _create_ a **virtual trigger** job that merely acts as a trigger event, removing the need to create a true job with container specs, a shimmed step and all the running implications of a full job.

**Details**

* Annotation-activated only for now
* Iconography: arrow job, much like the commit icon

**Comment by tkyi** [comment] 2021-06-03 19:13
probably related? https://github.com/screwdriver-cd/screwdriver/issues/1323

**Comment by renaud-vmg** [comment] 2021-06-03 19:39
That second one looks very similar, yes.

**Comment by kumada626** [comment] 2021-06-04 00:28
I think #1449 is related too.

**Comment by jithine** [comment] 2024-03-05 18:10
Closing this one as duplicate of https://github.com/screwdriver-cd/screwdriver/issues/1449

**Closed** 2024-09-29 06:20 UTC
Labels: feature
