### ISSUE TITLE
 Annoying "skip ci" commit logs shows on the screwdriver UI

### ISSUE THREAD

**Issue by puritys** [screwdriver-cd/screwdriver#1595] opened 2019-04-23 03:20 UTC
**What happened**:
The screwdriver UI shows many headless users commit log such as "[skip ci ] xxxx"

**What you expected to happen**:
Any commit log with the comment [skip ci ] shouldn't show on the  screwdriver UI.

**Comment by jithin1987** [comment] 2019-04-23 04:15
This is intended behavior. Without this, the latest event will not reflect the current state of Git. This can lead to unintended behavior if user tries to use the workflow graph to start builds. 

This is also a duplicate of https://github.com/screwdriver-cd/screwdriver/issues/1577 will continue discussion there.

**Closed by jithin1987** 2019-04-23 04:15 UTC
Labels: need more info
