### ISSUE TITLE
Delay between jobs

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#481] opened 2017-03-03 23:40 UTC
Was playing with some very fast builds, and it looks like there is a pretty long delay between the jobs in my pipeline: https://cd.screwdriver.cd/pipelines/94

Look at #dede44. The first job took 5 seconds and the second took 14. But the full pipeline took 57 seconds. In between the two jobs, it was sitting there with a clock symbol on the ui without an indication of why. It appears to be totally reproducible in this pipeline.

**Comment by d2lam** [comment] 2017-03-04 00:01
@jer  I think it was pulling the image. At the beginning of each build it would pull the image and UI doesn't really show that. 
Related to this issue: https://github.com/screwdriver-cd/screwdriver/issues/438

**Comment by stjohnjohnson** [comment] 2017-03-04 18:38
So far I'm unable to reproduce this with my own copy. But it would be good to get metrics of time between builds for an event so we could identify any gaps.

**Comment by jer** [comment] 2017-03-05 00:28
I see. Ok, so the 2 jobs must have run on different nodes and it didn't already have the image. I guess it would be nice to show some indication of what is happening, but I don't mind closing this issue if that is the explanation.

**Comment by d2lam** [comment] 2017-03-22 21:59
Closing this ticket. We can track the progress here: https://github.com/screwdriver-cd/screwdriver/issues/481

**Closed** 2017-03-22 21:59 UTC
Labels: type/bug
