### ISSUE TITLE
Git submodules are not up to date in branch-specific builds

### ISSUE THREAD

**Issue by marian-r** [screwdriver-cd/screwdriver#1262] opened 2018-08-23 13:47 UTC
**What happened**:

Branch-specific SD builds do not update the submodule to its latest state specified in that specific branch, but instead uses the state specified in master branch. SD clones the repo in master, clones submodules, switches to that specific branch to be used for build, but doesn't updated the submodules afterwards.

From SD log (truncated for readability):

```
...
Cloning git.com/myrepo, on branch master
...
Submodule 'path/to/submodule' (git@git.com:mysubmodule.git) registered for path 'path/to/submodule'
Cloning into 'path/to/submodule'...
...
Submodule path 'path/to/submodule': checked out '81f4ca57f96f52b71fa22df84061e826882c4199'
HEAD is now at 1568bdf My sample commit
Reset to 1568bdf708d47cd689ae113f19ec9603e519eac8
```

**What you expected to happen**:

SD builds should respect the submodule state in the branch-specific builds.

**How to reproduce it**:

1. Create a repo with a submodule, pointing to a commit (commit1).
1. Create SD pipeline, which will listen for changes in a separate branch (branch1)
1. Create a new branch (branch1), update the submodule to a new commit (commit2).
1. Commit, push.
1. SD will build the new branch (branch1), but the submodule will be in the state of commit1, instead of commit2.

Related to #1176 
Related to #1082

**Comment by catto** [comment] 2018-08-26 11:13
I have took a look at this issue and found that the root cause is here.
https://github.com/screwdriver-cd/scm-base/blob/master/index.js#L156
Its pipeline's branch name is set to `branch` variable here
https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L295
And finally SD clones your repo with pipeline's main branch.
https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L394

We should pass correct branch info to `getSetupCommand` or avoid causing the issue by running `git submodule init` and `git submodule update` again like PR builds. Submodules are already fetched and that needs only re-checkout. So I think latter one is reasonable for a quick fix.
https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L411-L415

**Comment by marian-r** [comment] 2018-09-28 10:27
@catto @jithin1987 is this now fixed? Can this be closed now?

**Comment by jithin1987** [comment] 2018-09-30 03:07
This should be fixed with https://github.com/screwdriver-cd/scm-github/pull/103 Closing this

**Closed by jithin1987** 2018-09-30 03:07 UTC
Labels: bug
