### ISSUE TITLE
500 error occurs if a repository is deleted

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#588] opened 2017-06-08 08:53 UTC
When I try to delete a pipeline that the associated repository is deleted, I got a 500 error from the API and there was no action in the UI. The pipeline wasn't deleted.
The API needs to avoid 500 errors and deletes the pipeline in such a situation.

I also tried sync buttons at that time, then a 404 error from GitHub was shown.
![image](https://user-images.githubusercontent.com/1608595/26918612-b6be38f0-4c6d-11e7-9331-cb8b9cebc292.png)
Should Screwdriver show a more friendly error message?

**Comment by d2lam** [comment] 2017-06-08 18:04
@catto  this is related to an opened issue we have: https://github.com/screwdriver-cd/screwdriver/issues/450

We should address it, but should we consolidate the issue?

**Comment by stjohnjohnson** [comment] 2017-06-09 16:23
Marking as duplicate of #450

**Closed by stjohnjohnson** 2017-06-09 16:23 UTC
Labels: status/duplicate

**Comment by catto** [comment] 2017-06-12 02:20
Oh I missed that issue 😭
