### ISSUE TITLE
Screwdriver should support container image pull configurations 

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2266] opened 2020-10-29 19:10 UTC
**What happened**:

Screwdriver executors currently doesn't support providing authorization when pulling containers for builds. Also container image is always pulled. This poses a problem with new Docker usage limits

**What you expected to happen**:

1. executors k8s & docker should support providing authorization against container registry.
2. cluster admin should also be able to define `imagePullPolicy` for container image

References

1. https://github.com/screwdriver-cd/executor-k8s/blob/d9d559c8d2bdbc12644fa99cfecc3f5580ccaef7/config/pod.yaml.hbs#L21
1. https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-in-the-cluster-that-holds-your-authorization-token

**How to reproduce it**:

1. https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/

**Comment by tkyi** [comment] 2020-11-03 21:45
Closing since it's a duplicate of https://github.com/screwdriver-cd/screwdriver/issues/2265

**Closed by tkyi** 2020-11-03 21:45 UTC
Labels: feature
