### ISSUE TITLE
[Feature Request] Checkout URL change history

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2634] opened 2022-01-17 08:03 UTC
**What happened**:

If the options screen can display the change history of Checkout URL, it is convenient in the following points.
- It will be a way to confirm that it has been changed. Currently there is no way for users to recognize the changes.
- The user who sees the Option screen can confirm the intention of the change to the person who made the change.

**What you expected to happen**:

The UI can display the change history (change datetime and user) of the Checkout URL.

**Comment by tkyi** [comment] 2022-01-18 19:41
Wonder if it would be good to have some audit log of all UI interactions eventually

**Comment by jithine** [comment] 2022-05-20 00:13
I think this is a duplicate of https://github.com/screwdriver-cd/screwdriver/issues/2700

**Closed by jithine** 2022-05-20 00:13 UTC
Labels: feature, ui
