### ISSUE TITLE
PR job not being created

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#246] opened 2016-10-06 01:33 UTC
This PR: https://github.com/screwdriver-cd/screwdriver/pull/237 does not have a job associated with it. 

Looked through the API: 
https://api.screwdriver.cd/v4/pipelines/27cec39c9baea6cf64c684479115300d22039b2a/jobs?archived=true

and 
https://api.screwdriver.cd/v4/pipelines/27cec39c9baea6cf64c684479115300d22039b2a/jobs?archived=false

It doesn't exist anywhere?!? Closed and reopened but still no job got created.

**Comment by stjohnjohnson** [comment] 2016-10-06 15:31
Okay, I figured it out.  We're giving a 401 signature invalid for the GitHub webhook using `hapi-github-webhooks`.  This is because the description contains invalid characters:

```
{
...
    "body": "Rewritten the functional tests for the Git Flow feature. This asserts the scenarios described in the `git-flow.feature` file. \r\n\r\n✅  Scenario: New Pull Request\r\n✅  Updated Pull Request\r\n✅  Closed Pull Request\r\n✅  New Commit\r\n\r\n",
...
}
```

**Comment by stjohnjohnson** [comment] 2016-10-06 15:37
@d2lam can you create a simple hapi service that can reproduce this exact problem?  And then file an issue with the plugin?

**Comment by d2lam** [comment] 2016-10-06 16:38
Wow you are right. I think it's because the checkbox is an image, not the `-[]` from github.

**Comment by stjohnjohnson** [comment] 2016-10-11 19:23
Opened a PR here: https://github.com/mhazy/hapi-github-webhooks/pull/2

Turns out it was an issue with UTF-8 encoding vs. Binary

**Comment by mhazy** [comment] 2016-10-12 03:15
Published a new version, you should be able to grab v1.0.3 now to close this. Thanks for the PR, cheers!

**Comment by stjohnjohnson** [comment] 2016-10-12 20:55
Thanks, @mhazy!  Works now!

**Closed by stjohnjohnson** 2016-10-12 20:55 UTC
Labels: priority/medium, type/bug
