### ISSUE TITLE
Weird log output in alpine images

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#672] opened 2017-07-28 18:20 UTC
On alpine based images, there is log output like `ho abc2134 $!`. This doesn't seem to effect anything in the build, it just leads to confusion as this isn't added by the user, and shouldn't be displayed.

**Comment by stjohnjohnson** [comment] 2018-03-12 07:07
Duplicate of https://github.com/screwdriver-cd/screwdriver/issues/559

**Closed by stjohnjohnson** 2018-03-12 07:07 UTC
Labels: bug
